# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.9.0
    working_directory: ~/engage-client
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test
  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.9.0
    working_directory: ~/engage-client
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: 
            name: Build for deploy
            command: |
              npm run build
              cd ..
              tar cj -f engage-client.tar.bz2 engage-client
      - add_ssh_keys:
            fingerprints:
              - "dc:9f:48:96:a1:76:08:e3:f9:5b:2e:c1:1e:5b:06:5a"
      - run: ssh-keyscan -t rsa -H engage.town >> ~/.ssh/known_hosts
      - run:
            name: Deploy over SSH
            command: |
                scp ./engage-client.tar.bz2 $SSH_USER@$SSH_HOST:/home/engage/engage-client.tar.bz2
workflows:
 version: 2
 build-and-deploy:
   jobs:
     - build
     - deploy:
         requires:
           - build
         filters:
           branches:
             only: eselkin/testing_scp